
  DESERT_RABBITS = {
                    karlsberg: ['Aaron Karlsberg', 'aaronkarlsberg'],
                    esmaili: ['Ali Esmaili', 'AESM'],
                    vaughan: ['Andrew Vaughan', 'avaughan89'],
                    field: ['Angela Field', 'angelafield'],
                    oztuncer: ['Banu Oztuncer', 'BanuD'],
                    vogelgesang: ['Brian Vogelgesang', 'kida001'],
                    giardina: ['Charles Giardina', 'cgardens'],
                    klos: ['Dan Klos', 'eclecticklos'],
                    kelley: ['Daniel Kelley', 'danimalkelley'],
                    cheng: ['Gabriel Cheng', 'gsccheng'],
                    sison: ['Hannah Sison', 'hsison'],
                    mcintyre: ['Jeremy McIntyre', 'jeremymcintyre'],
                    foley: ['John Foley', 'johnwfoley'],
                    luse: ['Jordan Luse', 'JLuse'],
                    won: ['Joseph Won', 'godspeedyoo'],
                    tice: ['Kindy Tice', 'ktice74'],
                    villwock: ['Matthew Villwock', 'mtvillwock'],
                    mears: ['Maxwell Mears', 'imears'],
                    chang: ['Michael Chang', 'mikeychang2'],
                    page: ['Michael Page', 'senormichaelpage'],
                    dharamcy: ['Nilesh Dharamcy', 'www-coder-in'],
                    salisbury: ['Rex Salisbury', 'resalisbury'],
                    fiallo: ['Richard Anthony Santin Fiallo', 'Ridou'],
                    buren: ['Rilke van Buren', 'rilkevb'],
                    idrisov: ['Ruslan Idrisov', 'ruslanid'],
                    chuang: ['Victoria Chuang', 'victoriachuang'],
                    fialho: ['Vivian Vieira Fialho', 'vivivf'],
                    tsang: ['William Tsang', 'kaawang']
                  }
